bookmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/',include('books.urls')),
    path('',HomeView,name='home')
]

books/urls.py
from django.urls import path, include
from .views import CreateBook, DetailView, ListBooks, DeleteView, UpdateView, SearchView

app_name = 'books'


urlpatterns = [
    path('create/',CreateBook,name='create'),
    path('list/',ListBooks,name='list'),
    path('detail/<str:pk>/',DetailView,name='detail'),
    path('delete/<str:pk>/',DeleteView,name='delete'),
    path('update/<str:pk>/',UpdateView,name='update'),
    path('search/',SearchView,name='search')


]

books/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Books(models.Model):
    bookname = models.CharField(max_length=50)
    price = models.FloatField()
    author_name = models.ManyToManyField(Author)
    genre = models.ForeignKey(Genre,on_delete=models.CASCADE)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.bookname

books/forms.py
from django import forms
from .models import Books

class BookForm(forms.ModelForm):
    class Meta():
        model = Books
        fields = ('bookname','price','description','author_name','genre')

books/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import BookForm
from .models import Books
# Create your views here.
#create the book
def CreateBook(request):
    form = BookForm()
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            print('book created')
        else:
            print('form is not valid')
    return render(request,'books/create.html',{"form":form})


# listing all the books
def ListBooks(request):
    context = {}
    context['books'] = Books.objects.all().order_by('bookname')
    return render(request,'books/list.html',context)


# gettting the detail of a particular book
def DetailView(request,pk):
    context = {}
    try:
        book = Books.objects.get(id=pk)
        context['book'] = book
    except:
        context['book'] = "empty, no such book"
        print("book doesn't exist")
    return render(request,'books/details.html',context)


# deleting a book
def DeleteView(request,pk):
    context = {}
    try:
        Books.objects.get(id=pk).delete()
        return HttpResponse('The book has been deleted')
    except:
        context['book'] = "empty, no such book"
        return HttpResponse('unable to delete')

def UpdateView(request,pk):
    context = {}
    if request.method == "POST":
        price = request.POST['price']
        description = request.POST['description']
        try:
            book = Books.objects.get(id=pk)
            book.price = price
            book.description = description
            book.save()
            return HttpResponse('Book Updated')
        except:
            context['book'] = "No such Book"
            return HttpResponse('No book')
    return render(request,'books/update.html',context)

def SearchView(request):
    context = {}
    if request.method == "POST":
        name = request.POST['book name']
        books = Books.objects.filter(bookname=name)
        context['books'] = books
        return render(request,'books/search.html',context)
    return render(request,'books/search.html',{})

def HomeView(request):
    return render(request,'home.html',{})

books/templates/books/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Curious Mind</title>
    <link rel="stylesheet" href="{% static 'css/book_base.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light">
      <a class='nav-elements' href="{% url 'home' %}"><button class="btn btn-dark">Home</button></a>
      <a class='nav-elements' href="{% url 'books:list' %}"><button class="btn btn-dark">List</button></a>
      <a class='nav-elements' href="{% url 'books:search' %}"><button class="btn btn-dark">Search</button></a>
      <a class='nav-elements' href="{% url 'books:create' %}"><button class="btn btn-dark">Add</button></a>
    </nav>
    {% block bodyblock %}
    {% endblock %}
  </body>
</html>

books/templates/books/create.html
{% extends './base.html' %}
  {% block bodyblock %}
  <br>
    <h2 align="center">Add New Book to Library</h2>
    <form class="create-form" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-dark">Create</button>
    </form>
  {% endblock %}

books/templates/books/details.html
{% extends './base.html' %}
  {% block bodyblock %}
  <br>
  <br>
    <div class=" container jumbotron ">

        <h1>{{ book.bookname }}</h1>
        <h5>About the book : </h5>
        <p>{{ book.description }}</p>
        <h4>Written By :</h4>
        <div class="container">
          {% for author in book.author_name.all %}
            <h5>{{ author }}</h5>
          {% endfor %}
        </div>
        <h1>Price : {{ book.price }}</h1>
        <h1> Genre : {{ book.genre }}</h1>
        <br>
        <a href="/books/delete/{{ book.id }}"><button class="btn btn-danger" type="button">Delete</button></a>
        <a href="/books/update/{{ book.id }}"><button class="btn btn-warning" type="button">Update</button></a>
    </div>


  {% endblock %}

books/templates/books/list.html
{% extends './base.html' %}
  {% block bodyblock %}
    <table class="table table-dark">
      <thead >
        <th>Name</th>
        <th>Price</th>
        <th>Author Name</th>
        <th>Genre</th>
        <th>View Detail</th>
      </thead>
      <tbody>
        {% for book in books %}
          <tr>
            <td>{{ book.bookname }}</td>
            <td>{{ book.price }}</td>
            {% for author in book.author_name.all %}
              <td>{{ author }}</td>
            {% endfor %}
            <td>{{ book.genre }}</td>
            <td><a href="/books/detail/{{ book.id }}"><button class="btn btn-outline-warning" type="button">Detail</button></a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endblock %}

books/templates/books/search.html
{% extends './base.html' %}
  {% block bodyblock %}
    <form class="search-form" method="POST">
      {% csrf_token %}
      <input id="search-input" type="text" name="book name" placeholder="Enter Book Name:">
      <br>
      <br>
      <button class="btn btn-dark" type="submit">Search</button>
    </form>
    <br>
    <br>
    <br>
    {% if books %}
    <table class="table">
      <thead class="thead-dark">
        <th>Name</th>
        <th>Price</th>
        <th>Author Name</th>
        <th>Genre</th>
        <th>View Detail</th>
    </thead>
      <tbody>
        {% for book in books %}
          <tr>
            <td>{{ book.bookname }}</td>
            <td>{{ book.price }}</td>
            {% for author in book.author_name.all %}
              <td>{{ author }}</td>
            {% endfor %}
            <td>{{ book.genre }}</td>
            <td><a href="/books/detail/{{ book.id }}"><button class="btn btn-outline-warning" type="button">Detail</button></a></td>
          </tr>
        {% endfor %}
      </tbody>
  </table>
    {% endif %}
  {% endblock %}

books/templates/books/update.html
{% extends './base.html' %}
  {% block bodyblock %}
    <form class="search-form" method="post">
      {% csrf_token %}
      <input type="text" name="price" placeholder="Enter Price:">
      <br>
      <br>
      <input type="text" name="description" placeholder="Enter Description:">
      <br>
      <br>
      <button class="btn btn-dark" type="submit">Update</button>
    </form>
  {% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Curious Mind</title>
    <link rel="stylesheet" href="{% static 'css/home_base.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light ">
      <a class='nav-elements' href="{% url 'home' %}"><button class="btn btn-dark">Home</button></a>
      <a class='nav-elements' href="{% url 'books:list' %}"><button class="btn btn-dark">List</button></a>
      <a class='nav-elements' href="{% url 'books:search' %}"><button class="btn btn-dark">Search</button></a>
      <a class='nav-elements' href="{% url 'books:create' %}"><button class="btn btn-dark">Add</button></a>
    </nav>
    {% block bodyblock %}
    {% endblock %}
  </body>
</html>

templates/home.html
{% extends './base.html' %}
  {% block bodyblock %}
    <h1 id="header" >Welcome to Curious Minds...!</h1>
    <h3>A place where curious minds come in search of their best friends</h3>
  {% endblock %}